:toc: macro
:toc-title:
:toclevels: 1

= TC-CBO-XXX

Casos de teste relacionados ao cálculo da métrica CBO (Coupling Between Object classes).

toc::[]

== TC-CBO-001

=== Cenário

Duas classes são definidas sem nenhuma proproedade ou método.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 0
| 2 | Class2 | 0
|===


== TC-CBO-002

=== Cenário

Três classes são definidas sem nenhuma proproedade ou método. Uma das classes herda de uma das outras.

=== Entrada

[, swift]
----
class Class1 { }
class Class2: Class1 { }
class Class3 { }
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 0
|===


== TC-CBO-003

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui declarações de variáveis do tipo de quatro das outras cinco classes definidas. Uma dessas variáveis é uma propriedade da classe; outra é declarada no inicializador; outra é definida em um método de instância; e a última é declarada em um método estático.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 {
    var variable1: Class1?

    init() {
        let object1: Class2?
    }

    func method1() {
        let object1: Class5?
    }

    static func method2() {
        let object1: Class6?
    }
}
class Class5 { }
class Class6 { }
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 0
| 4 | Class4 | 4
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-004

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui declarações de variáveis do tipo de três das outras cinco classes definidas. Todas essas declarações são feitas em uma extensão da classe. Uma das variáveis é uma propriedade da classe; outra é definida em um método de instância; e a última é declarada em um método estático.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 { }
class Class5 { }
class Class6 { }

extension Class4 {
    var variable1: Class1? { nil }

    func method1() {
        let object1: Class5?
    }

    static func method2() {
        let object1: Class6?
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 0
| 3 | Class3 | 0
| 4 | Class4 | 3
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-005

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui declarações de variáveis do tipo de quatro das outras cinco classes definidas. Duas dessas variáveis são propriedades da classe, sendo uma definida na declaração original da classe e a outra em uma extensão; outra é declarada no inicializador; outras duas são definidas em um método de instância, sendo uma na declaração original da classe e a outra em uma extensão; e as duas últimas são declaradas em um método estático, sendo uma na declaração original da classe e a outra em uma extensão.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 {
    var variable1: Class1?

    init() {
        let object1: Class2?
    }

    func method1() {
        let object1: Class5?
    }

    static func method2() {
        let object1: Class6?
    }
}
class Class5 { }
class Class6 { }

extension Class4 {
    var variable2: Class1? { variable1 }

    func method3() {
        let object1: Class5?
    }

    static func method4() {
        let object1: Class6?
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 0
| 4 | Class4 | 4
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-006

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui parâmetros do tipo de quatro das outras cinco classes definidas. Um desses parâmetros é de um inicializador; outros dois são definidos em um método de instância; e o último é parte de um método estático.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 {
    init(param1: Class1) { }

    func method1(param1: Class2, param2: Class5) { }

    static func method2(param1: Class6) { }
}
class Class5 { }
class Class6 { }
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 0
| 4 | Class4 | 4
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-007

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui parâmetros do tipo de quatro das outras cinco classes definidas. Todos esses parâmetros são definidos em métodos de uma extensão da classe. Dois dos parâmetros são definidos em um método de instância; e o último é parte de um método estático.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 { }
class Class5 { }
class Class6 { }

extension Class4 {
    func method1(param1: Class2, param2: Class5) { }

    static func method2(param1: Class6) { }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 0
| 2 | Class2 | 1
| 3 | Class3 | 0
| 4 | Class4 | 3
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-008

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui parâmetros do tipo de quatro das outras cinco classes definidas. Um desses parâmetros é de um inicializador; outros quatro são definidos em métodos de instância, sendo dois em um método declarado na definição original da classe e os outros dois em um método definido em uma extensão; e os dois últimos são parte de métodos estáticos, sendo um em um método declarado na definição original da classe e o outro em um método definido em uma extensão.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 {
    init(param1: Class1) { }

    func method1(param1: Class2, param2: Class5) { }

    static func method2(param1: Class6) { }
}
class Class5 { }
class Class6 { }

extension Class4 {
    func method3(param1: Class2, param2: Class5) { }

    static func method4(param1: Class6) { }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 0
| 4 | Class4 | 4
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-009

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui declarações de variáveis do tipo de quatro das outras cinco classes definidas, chamando o inicializador do tipo. Uma dessas variáveis é uma propriedade da classe; outra é declarada no inicializador; outra é definida em um método de instância; e a última é declarada em um método estático.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 {
    var variable1 = Class1()

    init() {
        let object1 = Class2()
    }

    func method1() {
        let object1 = Class5()
    }

    static func method2() {
        let object1 = Class6()
    }
}
class Class5 { }
class Class6 { }
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 0
| 4 | Class4 | 4
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-010

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui declarações de variáveis do tipo de duas das outras cinco classes definidas, chamando o inicializador do tipo. Todas essas declarações são feitas em uma extensão da classe. Uma das variáveis é definida em um método de instância; e a última é declarada em um método estático.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 { }
class Class5 { }
class Class6 { }

extension Class4 {
    func method1() {
        let object1 = Class5()
    }

    static func method2() {
        let object1 = Class6()
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 0
| 2 | Class2 | 0
| 3 | Class3 | 0
| 4 | Class4 | 2
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-011

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui declarações de variáveis do tipo de quatro das outras cinco classes definidas, chamando o inicializador do tipo. Uma dessas variáveis é uma propriedade da classe; outra é declarada no inicializador; outras duas são definidas em um método de instância, sendo uma na declaração original da classe e a outra em uma extensão; e as duas últimas são declaradas em métodos estáticos, sendo uma na declaração original da classe e a outra em uma extensão.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 {
    var variable1 = Class1()

    init() {
        let object1 = Class2()
    }

    func method1() {
        let object1 = Class5()
    }

    static func method2() {
        let object1 = Class6()
    }
}
class Class5 { }
class Class6 { }

extension Class4 {
    func method3() {
        let object1 = Class5()
    }

    static func method4() {
        let object1 = Class6()
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 0
| 4 | Class4 | 4
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-012

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui declarações de variáveis do tipo de quatro das outras cinco classes definidas, explicitanto o tipo e chamando o seu inicializador apenas com `.init()`. Duas dessas variáveis são propriedades da classe, sendo uma definida na declaração original da classe e a outra em uma extensão; outra é declarada no inicializador; outras duas são definidas em um método de instância, sendo uma na declaração original da classe e a outra em uma extensão; e as duas últimas são declaradas em métodos estáticos, sendo uma na declaração original da classe e a outra em uma extensão.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4 {
    var variable1: Class1 = .init()

    init() {
        let object1: Class2 = .init()
    }

    func method1() {
        let object1: Class5 = .init()
    }

    static func method2() {
        let object1: Class6 = .init()
    }
}
class Class5 { }
class Class6 { }

extension Class4 {
    var variable2: Class1 { variable1 }

    func method3() {
        let object1: Class5 = .init()
    }

    static func method4() {
        let object1: Class6 = .init()
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 0
| 4 | Class4 | 4
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


== TC-CBO-013

=== Cenário

Seis classes são definidas. Cinco delas não possui nenhuma proproedade ou método. Uma delas possui declarações de variáveis do tipo de quatro das outras cinco classes definidas e parâmetros do tipo de duas das outras cinco classes definidas. Algumas das declarações explicitam o tipo da variável, outras não. Algumas delas inicializam o valor chamando um inicializador. Algumas estão na definição original da classe e outras em uma extensão.

=== Entrada

[, swift]
----
class Class1 { }
class Class2 { }
class Class3 { }
class Class4: Class1 {
    let variable1: Class1
    var variable2 = Class2()

    init(variable1: Class1) {
        self.variable1 = variable1
    }

    func method1(param1: Class5) { }

    static func method2() {
        let object1: Class6 = .init()
    }
}
class Class5 { }
class Class6 { }

extension Class4 {
    var variable3: Class2 { variable2 }

    func method3() {
        let object1: Class5 = .init()
    }

    static func method4() {
        let object1: Class6 = .init()
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | CBO

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 0
| 4 | Class4 | 4
| 5 | Class5 | 1
| 6 | Class6 | 1
|===


// TODO: Adicionar testes pra classes definidas dentro de outras
