:toc: macro
:toc-title:
:toclevels: 1

= TC-DIT-XXX

Casos de teste relacionados ao cálculo da métrica DIT (Depth of Ingeritance).

toc::[]

== TC-DIT-001

=== Cenário

Quatro classes são definidas. A primeira não herda de nenhuma outra classe. As outras herdam da classe anterior, sequencialmente.

=== Entrada

[, swift]
----
class Class1 { }
class Class2: Class1 { }
class Class3: Class2 { }
class Class4: Class3 { }
----

=== Resultado

[%autowidth]
|===
| # | Class  | DIT

| 1 | Class1 | 0
| 2 | Class2 | 1
| 3 | Class3 | 2
| 4 | Class4 | 3
|===


== TC-DIT-002

=== Cenário

Quatro classes são definidas. A primeira herda de uma outra classe definida fora do escopo analisado. As outras herdam da classe anterior, sequencialmente.

=== Entrada

[, swift]
----
import Foundation

class Class1: NSObject { }
class Class2: Class1 { }
class Class3: Class2 { }
class Class4: Class3 { }
----

=== Resultado

[%autowidth]
|===
| # | Class  | DIT

| 1 | Class1 | 0
| 2 | Class2 | 1
| 3 | Class3 | 2
| 4 | Class4 | 3
|===


== TC-DIT-003

=== Cenário

Quatro classes são definidas. A primeira não herda de classe nenhuma e implementa um protocolo. As outras herdam da classe anterior, sequencialmente.

=== Entrada

[, swift]
----
protocol Protocol1 { }

class Class1: Protocol1 { }
class Class2: Class1 { }
class Class3: Class2 { }
class Class4: Class3 { }
----

=== Resultado

[%autowidth]
|===
| # | Class  | DIT

| 1 | Class1 | 0
| 2 | Class2 | 1
| 3 | Class3 | 2
| 4 | Class4 | 3
|===


== TC-DIT-004

=== Cenário

Quatro classes são definidas. A primeira não herda de nenhuma outra classe. As outras herdam da classe anterior, sequencialmente. Cada classe é definida em um arquivo diferente.

=== Entrada

Class1.swift:
[, swift]
----
class Class1 { }
----

Class2.swift:
[, swift]
----
class Class2: Class1 { }
----

Class3.swift:
[, swift]
----
class Class3: Class2 { }
----

Class4.swift:
[, swift]
----
class Class4: Class3 { }
----

=== Resultado

[%autowidth]
|===
| # | Class  | DIT

| 1 | Class1 | 0
| 2 | Class2 | 1
| 3 | Class3 | 2
| 4 | Class4 | 3
|===


== TC-DIT-005

=== Cenário

Uma classe definida dentro de outra classe herda de classe definida dentro de outra classe que foi definida dentro de outra classe.
Onde está definida a superclasse também tem outras duas classes que herdam dela. Uma delas usa o identificador "simples" da superclasse, enquanto a outra usa o identificador "completo".

=== Entrada

[, swift]
----
class Class1 {
    class Class1_1 {
        class Class1_1_1 { }
        class Class1_1_2: Class1_1_1 { }
        class Class1_1_3: Class1.Class1_1.Class1_1_1 { }
    }
}
class Class2 {
    class Class2_1: Class1.Class1_1.Class1_1_1 { }
}
----

=== Resultado

[%autowidth]
|===
| # | Class  | DIT

| 1 | Class1        | 0
| 2 | Class1_1      | 0
| 3 | Class1_1_1    | 0
| 4 | Class1_1_2    | 1
| 5 | Class1_1_3    | 1
| 6 | Class2        | 0
| 7 | Class2_1      | 1
|===
