:toc: macro
:toc-title:
:toclevels: 1

= TC-LCOM-XXX

Casos de teste relacionados ao cálculo da métrica LCOM (Lack of Cohesion in Methods).

toc::[]

== TC-LCOM-001

=== Cenário

Uma classe não possui nenhuma variável e define três métodos de instância e um método estático.

=== Entrada

[, swift]
----
class Class1 {
    func method1() { }
    func method2() { }
    func method3() { }

    static func method4() { }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 3
|===


== TC-LCOM-002

=== Cenário

Uma classe possui uma variável de instância e define três métodos de instância. Dois dos métodos acessam a variável.

=== Entrada

[, swift]
----
class Class1 {
    var variable1: Double = 42.0

    func method1() {
        print(variable1)
    }
    func method2() -> Double {
        variable1
    }
    func method3() { }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 2
|===


== TC-LCOM-003

=== Cenário

Uma classe possui uma variável de instância, uma variável estática e define três métodos de instância. Dois dos métodos acessam a variável de instância. Um desses dois e mais o método restante acessam a variável estática.

=== Entrada

[, swift]
----
class Class1 {
    var variable1: Double = 42.0

    static var variable2 = true

    func method1() {
        print(variable1)
        print(Self.variable2)
    }
    func method2() -> Double {
        variable1
    }
    func method3() {
        if Self.variable2 {
            print("yes")
        }
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 2
|===


== TC-LCOM-004

=== Cenário

Uma classe possui uma variável de instância, uma variável estática, três métodos de instância e um método estático. Dois dos métodos de instância acessam a variável de instância. Um desses dois, o método de instância restante e o método estático acessam a variável estática.

=== Entrada

[, swift]
----
class Class1 {
    var variable1: Double = 42.0

    static var variable2 = true

    func method1() {
        print(variable1)
        print(Self.variable2)
    }
    func method2() -> Double {
        variable1
    }
    func method3() {
        if Self.variable2 {
            print("yes")
        }
    }

    static func method4() {
        if Self.variable2 {
            print("yes")
        }
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 2
|===


== TC-LCOM-005

=== Cenário

Uma classe possui quatro variáveis de instância e três métodos de instância. Um dos métodos acessa uma variável que não é acessada por nenhum dos outros métodos. Um outro método acessa outra variável que também não é acessada por nenhum outro método e mais uma variável que é acessada pelo terceiro método. O terceiro método acessa duas variáveis.

=== Entrada

[, swift]
----
class Class1 {
    var variable1: Double = 42.0
    var variable2 = true
    var variable3 = "something"
    var variable4 = [1, 2, 3]

    func method1() {
        print(variable1)
    }
    func method2() {
        if variable2 {
            print(variable3)
        }
    }
    func method3() {
        for _ in variable4 {
            print(self.variable3)
        }
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 2
|===


== TC-LCOM-006

=== Cenário

Uma classe possui quatro variáveis de instância e três métodos de instância. O primeiro método acessa uma variável que não é acessada por nenhum dos outros métodos e mais uma que é acessada também pelo segundo método. O segundo método acessa essa variável acessada pelo primeiro método e mais uma que é acessada pelo terceiro método. O terceiro método acessa duas variáveis.

=== Entrada

[, swift]
----
class Class1 {
    var variable1: Double = 42.0
    var variable2 = true
    var variable3 = "something"
    var variable4 = [1, 2, 3]

    func method1() {
        if variable2 {
            print(variable1)
        }
    }
    func method2() {
        if variable2 {
            print(variable3)
        }
    }
    func method3() {
        for _ in variable4 {
            print(self.variable3)
        }
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 1
|===


== TC-LCOM-007

=== Cenário

Uma classe possui quatro variáveis de instância e três métodos de instância. Um dos métodos acessa uma variável que não é acessada por nenhum dos outros métodos e mais uma variável que é acessada pelo segundo método. O segundo método acessa duas variáveis: uma acessada pelo primeiro método e outra que também é acessada pelo terceiro método. O terceiro método acessa duas variáveis.

=== Entrada

[, swift]
----
class Class1 {
    var variable1: Double = 42.0
    var variable2 = true
    var variable3 = "something"
    var variable4 = [1, 2, 3]
}

extension Class1 {
    func method1() {
        if variable2 {
            print(variable1)
        }
    }
    func method2() {
        if variable2 {
            print(variable3)
        }
    }
    func method3() {
        for _ in variable4 {
            print(self.variable3)
        }
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 1
|===


== TC-LCOM-008

=== Cenário

Uma classe possui quatro variáveis de instância e três métodos de instância. Um desses métodos é definido em uma extensão da classe. O primeiro método acessa uma variável que não é acessada por nenhum dos outros métodos e mais uma variável que é acessada pelo segundo método. O segundo método acessa duas variáveis: uma acessada pelo primeiro método e outra que também é acessada pelo terceiro método. O terceiro método acessa duas variáveis.

=== Entrada

[, swift]
----
class Class1 {
    var variable1: Double = 42.0
    var variable2 = true
    var variable3 = "something"
    var variable4 = [1, 2, 3]

    func method1() {
        if variable2 {
            print(variable1)
        }
    }

    func method2() {
        if variable2 {
            print(variable3)
        }
    }
}

extension Class1 {
    func method3() {
        for _ in variable4 {
            print(self.variable3)
        }
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 1
|===


== TC-LCOM-009

=== Cenário

Uma classe possui quatro variáveis de instância e um método de instância. Esse método acessa uma das variáveis.

Uma outra classe herda da primeira e possui mais dois métodos de instância. Um desses métodos acessa uma variável que não é acessada por nenhum dos outros métodos e mais uma variável que é acessada pelo último método. O último método acessa essa variável acessada pelo outro método da classe filha e mais uma que não é acessada por nenhum dos outros métodos.

=== Entrada

Class1.swift:
[, swift]
----
class Class1 {
    var variable1: Double = 42.0
    var variable2 = true
    var variable3 = "something"
    var variable4 = [1, 2, 3]

    func method1() {
        print(variable1)
    }
}
----

Class2.swift:
[, swift]
----
class Class2: Class1 {
    func method2() {
        if variable2 {
            print(variable3)
        }
    }
    func method3() {
        for _ in variable4 {
            print(self.variable3)
        }
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 1
| 2 | Class2 | 1
|===


== TC-LCOM-010

=== Cenário

Uma classe é definida sem nenhuma variável ou método.

=== Entrada

[, swift]
----
class Class1 { }
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 0
|===


== TC-LCOM-011

=== Cenário

Um método de uma classe acessa uma variável de instância e, em linhas posteriores à esse acesso, declara uma variável local com o mesmo nome da variável de instância e acessa essa variável local. Um outro método da mesma classe também acessa a mesma variável de instância.

=== Entrada

[, swift]
----
class Class1 {
    var variable1 = false

    func method1() {
        print(variable1)
        let variable1 = true
        print(variable1)
    }

    func method2() {
        print(self.variable1)
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 1
|===


== TC-LCOM-012

=== Cenário

Um método de uma classe declara uma variável local com o mesmo nome de uma variável de instância e acessa essa variável local. Um outro método da mesma classe também acessa a variável de instância de mesmo nome.

=== Entrada

[, swift]
----
class Class1 {
    var variable1 = false

    func method1() {
        let variable1 = true
        print(variable1)
    }

    func method2() {
        print(self.variable1)
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 2
|===


== TC-LCOM-013

=== Cenário

Um método de uma classe declara uma variável local com o mesmo nome de uma variável de instância e acessa essa variável local. Em uma linha posterior à declaração da variável local, o mesmo método acessa a variável de instância utilizando `self`. Um outro método da mesma classe também acessa a variável de instância.

=== Entrada

[, swift]
----
class Class1 {
    var variable1 = false

    func method1() {
        let variable1 = true
        print(variable1)
        print(self.variable1)
    }

    func method2() {
        print(self.variable1)
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 1
|===


== TC-LCOM-014

=== Cenário

Uma classe possui uma variáveis de instância e dois métodos de instância. Um dos métodos acessa a variável sem usar `self.` e o outro método acessa a mesma variável utilizando `self.`.

=== Entrada

[, swift]
----
var variable1 = true

class Class1 {
    var variable1 = false

    func method1() {
        print(variable1)
    }

    func method2() {
        print(self.variable1)
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 1
|===


== TC-LCOM-015

=== Cenário

Uma variavél global é definida.

Uma classe possui uma variáveis de instância com o mesmo identificador da variável global e dois métodos de instância. Um dos métodos acessa a variável global usando `<nome-do-módulo>.` e o outro método acessa a variável de instância da classe utilizando `self.`.

=== Entrada

[, swift]
----
var variable1 = true

class Class1 {
    var variable1 = false

    func method1() {
        print(Module1.variable1)
    }

    func method2() {
        print(self.variable1)
    }
}
----

=== Resultado esperado

[%autowidth]
|===
| # | Class  | LCOM

| 1 | Class1 | 2
|===

