:toc: macro
:toc-title:
:toclevels: 1

= TC-NOC-XXX

Casos de teste relacionados ao cálculo da métrica NOC (Number of Children).

toc::[]

== TC-NOC-001

=== Cenário

Três classes herdam de uma classe que não herda de nenhuma outra.

=== Entrada

[, swift]
----
class Class1 { }
class Class2: Class1 {}
class Class3: Class1 {}
class Class4: Class1 {}
----

=== Resultado

[%autowidth]
|===
| # | Class  | NOC

| 1 | Class1 | 3
| 2 | Class2 | 0
| 3 | Class3 | 0
| 4 | Class4 | 0
|===


== TC-NOC-002

=== Cenário

Três classes herdam de uma classe que herda de uma outra classe.

=== Entrada

[, swift]
----
class Class1 { }
class Class2: Class1 {}
class Class3: Class2 {}
class Class4: Class2 {}
class Class5: Class2 {}
----

=== Resultado

[%autowidth]
|===
| # | Class  | NOC

| 1 | Class1 | 1
| 2 | Class2 | 3
| 3 | Class3 | 0
| 4 | Class4 | 0
| 5 | Class5 | 0
|===


== TC-NOC-003

=== Cenário

Três classes herdam de uma classe que herda de uma outra classe definida fora do escopo analisado.

=== Entrada

[, swift]
----
import Foundation

class Class1: NSObject { }
class Class2: Class1 {}
class Class3: Class1 {}
class Class4: Class1 {}
----

=== Resultado

[%autowidth]
|===
| # | Class  | NOC

| 1 | Class1 | 3
| 2 | Class2 | 0
| 3 | Class3 | 0
| 4 | Class4 | 0
|===


== TC-NOC-004

=== Cenário

Três classes herdam de uma classe que não herda de classe nenhuma e implementa um protocolo.

=== Entrada

[, swift]
----
protocol Protocol1 {}

class Class1: Protocol1 { }
class Class2: Class1 {}
class Class3: Class1 {}
class Class4: Class1 {}
----

=== Resultado

[%autowidth]
|===
| # | Class  | NOC

| 1 | Class1 | 3
| 2 | Class2 | 0
| 3 | Class3 | 0
| 4 | Class4 | 0
|===


== TC-NOC-005

=== Cenário

Três classes herdam de uma classe que não herda de nenhuma outra. Cada classe é definida em um arquivo diferente.

=== Entrada

Class1.swift:
[, swift]
----
class Class1 { }
----

Class2.swift:
[, swift]
----
class Class2: Class1 {}
----

Class3.swift:
[, swift]
----
class Class3: Class1 {}
----

Class4.swift:
[, swift]
----
class Class4: Class1 {}
----

=== Resultado

[%autowidth]
|===
| # | Class  | NOC

| 1 | Class1 | 3
| 2 | Class2 | 0
| 3 | Class3 | 0
| 4 | Class4 | 0
|===


== TC-NOC-006

=== Cenário

Uma classe definida dentro de outra classe herda de classe definida dentro de outra classe que foi definida dentro de outra classe.
Onde está definida a superclasse também tem outras duas classes que herdam dela. Uma delas usa o identificador "simples" da superclasse, enquanto a outra usa o identificador "completo".

=== Entrada

[, swift]
----
class Class1 {
    class Class1_1 {
        class Class1_1_1 { }
        class Class1_1_2: Class1_1_1 { }
        class Class1_1_3: Class1.Class1_1.Class1_1_1 { }
    }
}
class Class2 {
    class Class2_1: Class1.Class1_1.Class1_1_1 { }
}
----

=== Resultado

[%autowidth]
|===
| # | Class                         | NOC

| 1 | Class1                        | 0
| 2 | Class1.Class1_1               | 0
| 3 | Class1.Class1_1.Class1_1_1    | 3
| 4 | Class1.Class1_1.Class1_1_2    | 0
| 5 | Class1.Class1_1.Class1_1_3    | 0
| 6 | Class2                        | 0
| 7 | Class2_1                      | 0
|===


== TC-NOC-007

=== Cenário

Quatro classes são definidas. A primeira não herda de nenhuma outra classe. As outras herdam da classe anterior, sequencialmente.

=== Entrada

[, swift]
----
class Class1 { }
class Class2: Class1 { }
class Class3: Class2 { }
class Class4: Class3 { }
----

=== Resultado

[%autowidth]
|===
| # | Class  | NOC

| 1 | Class1 | 1
| 2 | Class2 | 1
| 3 | Class3 | 1
| 4 | Class4 | 0
|===
